name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Bandit
      run: |
        pip install bandit
    - name: Run Bandit
      run: |
        bandit -r ctf2/hospital -f json -o bandit_report.json || true
    - name: Upload Bandit Report
      uses: actions/upload-artifact@v3
      with:
        name: bandit_report
        path: bandit_report.json
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python-3.7@master
      env:
        SNYK_TOKEN: ${{ secrets.SYNK_TOKEN }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    
